### ISSUE TITLE
Checkmarx Integration lookup Issue

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/Dev#180]
There is an issue in the way Checkmarx lookup is performed in TM. We are relying on the contains method, so CWE 11 will be contained in CWE 117 etc.

We need to fix it to match the exact CWE provided by Chekmarx.

**Comment by roman87** [comment]
@michaelhidalgo I think this issue belongs in TeamMentor/master

**Comment by michaelhidalgo** [comment]
Alright, yeah, let me move it right away!

**Comment by michaelhidalgo** [comment]
Closing this one since it is being tracked here https://github.com/TeamMentor/Master/issues/958
